- .github/actions/deploy/action.yml
Previously if the `commit.message` of the `SHA` was very long:
- `pull_request`: with a lot of information the commit message (dependabot, feature, etc.)
This was creating a very large `githubCommitMessage` environment variable which was breaking (specifically) production builds from `main`:
```sh
Error! The total size of all Environment Variables (9.1KB) exceeds 4KB.
[51](https://github.com/JeromeFitz/websites/runs/5115282111?check_suite_focus=true#step:6:51)
Learn More: https://vercel.link/env-vars-limit
```
Being that there are less than 10 environment variables for this website, the hope is this was the culprit.
I am also adding a lot of information in this PR to ensure we are well over the `50` character limit which is now imposed by it truncating in the forked repo.
If this works …
> 💚  (actions) 🍽️  of `deploy-to-vercel-action` test

- sites/jeromefitzgerald.com/src/pages/api/revalidate/index.ts
I know this was `unstable_revalidate` but removing this during a patch release is still bogus.
> 🚑️  (next) unstable_revalidate => revalidate [b]

- sites/jeromefitzgerald.com/next.config.js
- sites/jeromefitzgerald.com/src/components/Banner/Banner.tsx
- sites/jeromefitzgerald.com/src/components/Header/Header.tsx
- Displays `Banner` if the Environment Variable is set (`NEXT_PUBLIC__EVENT_UPCOMING_FLAG`)
- 💩 do not want to show `Banner` if no Events (constant loading)
- 💡 ideally would have a fall-back blog post or behavior and remove this
- When showing an Event in the Banner should show the _next_ event
- 💡 maybe down the line this is a slide show of all upcoming
> 🐛  banner next event; ⛳ banner flag

- packages/next-notion/src/app/components/image.tsx
This is a **hack** which should be replaced when `next/image` gets this functionality out of the box, or if there is a more straight-forward to do the following dynamically:
- https://beta.nextjs.org/docs/api-reference/metadata#resource-hints
> 💩  (next) NICE-24 priority image hack, preload image [b]

- sites/jeromefitzgerald.com/src/app/(cache)/getDataFromCache.ts
- sites/jeromefitzgerald.com/src/app/(notion)/(config)/utils/getDatabaseQuery.ts
- sites/jeromefitzgerald.com/src/app/(notion)/(config)/utils/getPageDataFromNotion.ts
- sites/jeromefitzgerald.com/src/app/(notion)/about/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/books/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/colophon/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/contact/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/events/[[...catchAll]]/Event.Listing.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/events/[[...catchAll]]/Event.Slug.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/events/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/music/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/people/[[...catchAll]]/People.Listing.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/people/[[...catchAll]]/Person.Slug.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/people/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/podcasts/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/shows/[[...catchAll]]/Show.Listing.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/shows/[[...catchAll]]/Show.Slug.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/shows/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/api/v1/draft-disable/route.ts
- sites/jeromefitzgerald.com/src/app/api/v1/draft/route.ts
- sites/jeromefitzgerald.com/src/app/api/v1/revalidate/route.ts
- sites/jeromefitzgerald.com/src/app/page.tsx
- sites/jeromefitzgerald.com/src/app/playground/kitchen-sink/page.tsx
Change from `preview` to `draft`
- ref: https://nextjs.org/docs/app/building-your-application/configuring/draft-mode
To-Do:
Note:
- This does not currently work for any `pages` segment in root.
> ✨  (poc) NICE-57 next => draft + revalidate [b]

- packages/shared/src/components/Analytics/Analytics.tsx
- packages/shared/src/components/Analytics/Vercel.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/people/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/layout.tsx
- sites/jeromefitzgerald.com/src/app/playground/design-system/page.tsx
- sites/jeromefitzgerald.com/src/app/playground/kitchen-sink/page.tsx
- sites/jeromefitzgerald.com/src/app/playground/open-graph/page.tsx
- sites/jeromefitzgerald.com/src/app/playground/plaiceholder/page.tsx
- sites/jeromefitzgerald.com/src/components/Notion/Notion.Config.ts
- sites/jeromefitzgerald.com/src/components/Providers/Providers.client.tsx
- sites/jeromefitzgerald.com/src/components/Providers/RouterEventProvider.client.tsx
- I mean, I think, heh. Fathom works just fine. Vercel stopped after perf updates apparently
- Introduced in `nextd@13.4.10`
- With above `notFound` can finally tell where this warning was coming from G2G back
Aye welcome back Vercel Analytics (from Preview Environment):
> 🐛  (analytics) vercel/fathom; NEXT_DYNAMIC_NO_SSR_CODE [b]

- packages/next-config/next.config.mjs
Issue is storybook@7 ships with `swc` and need to exclude it since
production does not need it and ... not sure what is happening.
```bash
Serverless Function's page: ...
Large Dependencies                                                      Uncompressed size  Compressed size
node_modules/.pnpm/@swc+core-linux-x64-musl@1.3.70                               51.77 MB         17.18 MB
node_modules/.pnpm/@swc+core-linux-x64-gnu@1.3.70                                44.48 MB         14.62 MB
node_modules/.pnpm/sharp@0.32.3                                                   16.1 MB          6.95 MB
node_modules/.pnpm/next@13.4.11-canary.1_react-dom@18.2.0_react@18.2.0           21.98 MB          5.43 MB
node_modules/.pnpm/@esbuild+linux-x64@0.18.8                                      8.77 MB …
```
> 🔧 (next-config) NICE-64 outputFileTracingExcludes swc

- packages/design-system/package.json
- packages/jest-config/package.json
- packages/next-config/package.json
- packages/next-notion/package.json
- packages/shared/package.json
- pnpm-lock.yaml
- sites/jeromefitzgerald.com/package.json
- sites/jeromefitzgerald.com/src/app/_next/preload-resources.tsx
- sites/jeromefitzgerald.com/src/app/layout.tsx
- sites/jeromefitzgerald.com/src/components/Banner/Banner.tsx
- ⬆️  (deps) next@13.4.20-canary.11
- Hack for Preload Resources `next/head` is 👻
- 🩹 override cache hack 
- I weep that this happens from time to time with listings and the circular logic
- Please fix in next 30 days
This PR (still) does not pull from latest DB to make this dynamic
- And need to run a build with `OVERRIDE_CACHE` to re-fill DB properly
> ⬆️  (next) next@13.4.20-canary.11, 🐛 PreloadResources [b]

- sites/jerandky.com/src/app/api/rss/podcasts/jer-and-ky-and-guest/route.ts
- sites/jerandky.com/src/app/api/rss/podcasts/knockoffs/route.ts
- sites/jeromefitzgerald.com/src/app/api/rss/podcasts/[slug]/route.ts
> 🐛  (rss) atom:self link to rss feed not href url [skip ci]

- package.json
- packages/design-system/src/components/Caption/Caption.tsx
- packages/shared/package.json
- patches/@radix-ui__themes@3.0.0-rc.10.patch
- pnpm-lock.yaml
- sites/jeromefitzgerald.com/src/app/(notion)/_config/config.ts
- sites/jeromefitzgerald.com/src/app/(notion)/music/_components/Music.client.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/music/page.tsx
This is a temporary patch to see about _ensuring_ `@radix-ui/themes` uses **esm**.
This does enable tree-shaking to an extent on the build. 
(Still work to do with the `.css` import to limit un-used components. But is not a priority.)
This may be solely because of the `tsconfig` locally too. 🤔
- I believe so because was not able to move `next` awhile back to `NodeNext`
- This will be a hack until I can revisit that probably
---
Additional Update while we are here
> 🩹  (deps) NICE-79 radix-ui/themes force esm [b]

- packages/shared/src/components/Notion/Blocks/Image.client.tsx
- sites/jeromefitzgerald.com/src/app/_components/Page.Home.tsx
- sites/jeromefitzgerald.com/src/components/Quote/Quote.tsx
One image in particular was generating a warning on dev, and minified react error on prod.
> 🐛  NICE-87 next/image w/h for quote [b]

- sites/jeromefitzgerald.com/src/components/Banner/Banner.tsx
In looking at `#2339` this came up as an optimization. At first it looked promising that it was it, but it not 😅 
Does not close `#2339`
> 🐛  memo-ize banner [skip ci]

- package.json
- pnpm-lock.yaml
Both should be removed with next `storybook` update
> 📌  (deps) storybook overrides [skip ci]

- sites/.gitignore
Well this is certainly a mess since Google sold to Squarespace, isn't it?
🤡 👞 🤡 👞 🤡 👞 🤡 👞 🤡 👞 🤡 👞 🤡 👞 🤡 👞 🤡 👞 🤡 👞 🤡 👞 🤡 👞 🤡 👞  
Static code hidden locally, but we moved over some specific domains to Vercel and DNSimple.
And my long time favorites are seeing if they do migrate over (SPOILER: THEY WILL NOT):
If any of these _other_ long-term static pages do not work (spoiler: THEY WILL NOT SINCE THEY DO NOT MOVE OVER ANY DNS INFORMATION), just move them to V/D or Redirect to `jeromefitzgerald.com/shows/[SITE_NAME_HERE]`.
But yea, guess what, Squarespace won't let redirects to domains outside of their space apparently. As I have tried with:
- 6 OTHER DOMAINS NOT LISTED HERE 🔥 🔥 🔥 🔥 🔥
> 💩  google domains migration [skip ci]

- sites/jeromefitzgerald.com/src/app/(notion)/music/_components/Music.client.tsx
- sites/jeromefitzgerald.com/src/store/index.tsx
Swap to default setting of: `medium_term`
Empty results on `./music` looks odd.
Have been using more `radiooooooooooooooOOoOOooooooo`, `bandcamp`, and "old-school" MP3s/FLAC.
> 🩹  (spotify) medium_term [b]

- .husky/pre-commit
- .husky/prepare-commit-msg
With `9.1.0` this is no longer necessary
> 🐛  (husky) remove pwd [skip ci]

- package.json
- pnpm-lock.yaml
- sites/jerandky.com/src/components/Providers/Providers.client.tsx
- sites/jeromefitzgerald.com/src/components/Providers/Providers.tsx
- sites/jeromefitzgerald.com/src/store/index.tsx
> ⬆️ (deps) eslint-config@5.0.0-canary.11 [skip ci]

- sites/jeromefitzgerald.com/src/app/(notion)/_config/Event.utils.ts
- sites/jeromefitzgerald.com/src/app/(notion)/events/[[...catchAll]]/_components/Event.Slug.tsx
(╯°□°)╯︵ ┻━┻ `Slug.Preview`
```bash
join(["", "events", formatDate(dateSubtract(prop("Date"), 5, "hours"), "YYYY/MM/DD"), prop("Slug")], "/")
```
API User is UTC, so basically account for highest diff in Eastern Timezone with UTC instead of `1` day.
This seems to nly work with blowing out cache and doing a check for SEO Image now. (－‸ლ)
> 🐛  (notion) (╯°□°)╯︵ ┻━┻ Slug.Preview [b]

- sites/jeromefitzgerald.com/src/app/(notion)/currently/listening-to/_components/Music.client.tsx
- sites/jeromefitzgerald.com/src/app/api/v1/music/[slug]/route.ts
- sites/jeromefitzgerald.com/src/app/playground/2024/_components/Currently.Music.Client.tsx
- sites/jeromefitzgerald.com/src/utils/getKey.ts
Use `1` for **Homepage** (Homepage)
Use `50` for **Currently** (Recently Played)
API only allows going back ~50 records (which is the limit). Instead of finagling a way to dynamically load based on [`cursors.before|after`](https://developer.spotify.com/documentation/web-api/reference/get-recently-played) do the above.
If we ever want to limit back down to `10` and cycle through do some finagling via:
```bash
before: `${getUnixTime(_last(data).played_at)}000`
```
> 🐛  NICE-135 limit for recently-played [b]

- packages/next-notion/src/queries/getBlockChildrenData.ts
- packages/next-notion/src/queries/getDatabaseQuery.ts
Seems like adding `1` more event was the straw that broke the camel's back here.
But all the same probably _do not_ need to be caching so many events, I am with you upstash.
Look into breaking it down by years. To just grab the latest it would be more ideal to hit up:
`./notion/queries/events/events/[CURRENT_YEAR]`
Rather than _all of them_. So perhaps do that next. You can always then _join_ multiple years for longer-term. Heck even `CURRENT_YEAR-1` is probably fine.
> 🩹  (notion) page_size 50; !has_more if events [b]

- package.json
- pnpm-lock.yaml
Need to hold on upgrading further until `turbo@2.4.5|2.5.0` due to side issue with `eslint-config-turbo`.
> ⬆️  (deps) eslint-config@5.0.0-canary.39 [skip ci]
