- sites/jeromefitzgerald.com/src/components/Banner/Banner.tsx
- sites/jeromefitzgerald.com/src/components/Banner/index.ts
- sites/jeromefitzgerald.com/src/components/Header/Header.tsx
- sites/jeromefitzgerald.com/src/components/Layout/Layout.tsx
- sites/jeromefitzgerald.com/src/components/Link/Highlight.tsx
- sites/jeromefitzgerald.com/src/components/Link/index.ts
- sites/jeromefitzgerald.com/src/components/NavSkip/NavSkip.tsx
- sites/jeromefitzgerald.com/src/components/NavSkip/index.ts
- sites/jeromefitzgerald.com/src/config/notion.ts
- sites/jeromefitzgerald.com/src/lib/notion/app/routes/Events/Listing.tsx
This is still not dynamic from teh API as it is not a high priority. Though at the same time, when one starts doing more shows this would be nice to not think about, haha.
> 🐛  (notion) `EVENTS` infoType  ♻️  Header eject + Banner

- package.json
- packages/next-notion/package.json
- packages/shared/package.json
- sites/jeromefitzgerald.com/package.json
- yarn.lock
```sh
@jeromefitz/lint-staged@1.0.3
@jeromefitz/notion@3.2.1
turbo@1.2.15
```
ref: https://github.com/JeromeFitz/packages/pull/666
> ⬆️  notion hotfix (+ lint-staged, turbo) [b]

- sites/jeromefitzgerald.com/src/app/layout.tsx
- sites/jeromefitzgerald.com/src/components/Analytics/Analytics.tsx
- sites/jeromefitzgerald.com/src/components/Analytics/Fathom.tsx
- sites/jeromefitzgerald.com/src/components/Analytics/Vercel.tsx
- sites/jeromefitzgerald.com/src/components/Analytics/index.ts
- sites/jeromefitzgerald.com/src/components/Providers/Providers.tsx
Was not tracking because I think it was in a client component not server in root fo `app/layout`
> ♻️  (vercel) NICE-15 analytics via app/dir [skip ci]

- sites/jeromefitzgerald.com/src/app/(notion)/books/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/events/[[...catchAll]]/Listing.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/events/[[...catchAll]]/Slug.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/events/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/shows/[[...catchAll]]/Listing.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/shows/[[...catchAll]]/UpcomingEvents.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/shows/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/ListingShows.tsx
- sites/jeromefitzgerald.com/src/app/page.tsx
- sites/jeromefitzgerald.com/src/components/Analytics/Vercel.tsx
- sites/jeromefitzgerald.com/src/components/Footer/Footer.tsx
- sites/jeromefitzgerald.com/src/components/Music/Music.tsx
- sites/jeromefitzgerald.com/src/components/Music/NowPlaying/NowPlaying.tsx
- sites/jeromefitzgerald.com/src/components/Music/Top/Top.tsx
- sites/jeromefitzgerald.com/src/hooks/useNotion.ts
**Listing Rework**:
**Icon For Dev**:
> 🩹  NICE-16 Listing/Slug Rework; Analytics Dev; Icon (NEXT-790)

- .github/actions/lint/action.yml
- .github/renovate.json
- package.json
- packages/next-notion/package.json
- packages/next-notion/src/app/components/code.tsx
- packages/next-notion/src/getImage.ts
- packages/next-notion/src/getImages.ts
- packages/next-notion/src/getPodcastFeed.ts
- packages/next-notion/src/getStaticPropsCatchAll.ts
- packages/next-notion/src/helper.ts
- packages/shared/package.json
- pnpm-lock.yaml
- sites/jeromefitzgerald.com/package.json
```bash
@types/lodash@4.14.194
@types/react@18.0.35
@jeromefitz/conventional-gitmoji@3.3.6
@jeromefitz/design-system@4.2.0
@jeromefitz/eslint-config@1.1.14
@jeromefitz/lint-staged@1.1.9
@jeromefitz/prettier-config@1.1.6
@jeromefitz/release-notes-generator@1.2.9
rimraf@5.0.0
typescript@5.0.4
turbo@1.9.1
```
> ⬆️  (deps) turbo@1.9.1, typescript@5.0.4, jeromefitz/... [b]

- .github/workflows/pull.yml
- .github/workflows/push.yml
- Until we can speed this up take it out of the **build** and _only_ when requested
- This will return but we will be having a lot of builds in the next few and do not want to wait on this
- Separate issue will be created to identify how to improve timing
> 👷  (e2e) NICE-48 skip unless `e2e` provided in `[...]`

- packages/next-notion/src/queries/getDatabaseQuery.ts
- sites/jeromefitzgerald.com/src/app/(cache)/getCustom.ts
- sites/jeromefitzgerald.com/src/app/(notion)/(utils)/utils/getDatabaseQuery.ts
- sites/jeromefitzgerald.com/src/app/(notion)/(utils)/utils/getDatabaseQueryByDateRange.ts
- sites/jeromefitzgerald.com/src/app/(notion)/(utils)/utils/getPageData.ts
- sites/jeromefitzgerald.com/src/app/(notion)/about/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/books/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/colophon/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/contact/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/events/[[...catchAll]]/Event.Listing.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/events/[[...catchAll]]/Event.Slug.Venue.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/events/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/music/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/people/[[...catchAll]]/People.Listing.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/people/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/podcasts/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/shows/[[...catchAll]]/Show.Listing.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/shows/[[...catchAll]]/Show.UpcomingShows.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/shows/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/page.tsx
- sites/jeromefitzgerald.com/src/app/playground/kitchen-sink/page.tsx
- sites/jeromefitzgerald.com/src/components/Relations/Relations.Individual.tsx
Yup, forgot to put this back.
Quick hack to stop the Notion Gateway Errors please.
> ✨  NICE-55 cache layer before notion check [b]

- .github/actions/e2e/action.yml
- .github/workflows/pull.yml
- .github/workflows/push.yml
- README.md
- package.json
- packages/lighthouse-config/lighthouse.config.js
- sites/jeromefitzgerald.com/src/app/(notion)/(config)/utils/getMetadata.ts
- sites/jeromefitzgerald.com/src/app/layout.tsx
- sites/jeromefitzgerald.com/src/e2e/index.e2e.ts
```bash
~7m (12.x) => ~13m (13.x) => turned off => ~5m => ~3m => 1m35s
```
Going to turn back on :100:
Nice, last one was `~50s` of course I am sure `upstash` will now complain we are using the thing you pay for 😑 
📝  Note, lighthouse will not re-upload to GitHub if it was cached
> 👷  (gh-actions) attempt to cache playwright installs [b]

- packages/shared/src/notion/utils/getMetadata.ts
- sites/jeromefitzgerald.com/src/app/(notion)/_config/temp/generateMetadataCustom.ts
- sites/jeromefitzgerald.com/src/app/(notion)/about/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/books/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/colophon/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/contact/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/events/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/music/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/people/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/podcasts/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/shows/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/layout.tsx
- sites/jeromefitzgerald.com/src/app/page.tsx
quick way to get seo/og back
into fighting shape
> ⚡️  (next) NICE-59 generateMetaDataCustom 💩 [b]

- package.json
- pnpm-lock.yaml
until deps can update, handle it for them
> 📌  (deps) semver@6.3.1; semver@7.5.4 [skip ci]

- packages/design-system/package.json
- packages/jest-config/package.json
- packages/next-config/package.json
- packages/next-notion/package.json
- packages/shared/package.json
- packages/shared/src/components/Notion/Blocks/Image.client.tsx
- pnpm-lock.yaml
- sites/jeromefitzgerald.com/package.json
- sites/jeromefitzgerald.com/src/app/(notion)/events/[[...catchAll]]/_components/Event.Listing.tsx
- sites/jeromefitzgerald.com/src/app/layout.tsx
Actually, do not know if times will go down (that may be an Image size thing at this point).
But removing a hack is always nice.
> ⬆️  NICE-60 next@13.4.11-canary.0 next/image preload [skip ci]

- sites/jerandky.com/src/components/Footer/Footer.tsx
- sites/jeromefitzgerald.com/src/components/Footer/Footer.tsx
simple change to get the current year without the need to update it each new year
> fix: update `Footer.tsx` to get current year

- packages/next-config/next.config.mjs
- sites/jeromefitzgerald.com/src/components/Banner/Banner.tsx
- sites/jeromefitzgerald.com/src/components/NowReading/NowReading.tsx
Whoops. Shout out Tanker.
I am ... 😜 ... not going to get this new version out anytime soon it looks like.
> 🩹  30 day event fix [b]

- packages/next-notion/package.json
- packages/next-notion/src/utils/getAwsImage.ts
- pnpm-lock.yaml
- sites/jeromefitzgerald.com/package.json
Stop-gap until official upgrade for `date-fns|date-fns-tz@3`
- Reference: https://github.com/JeromeFitz/date-fns-tz/pull/3
> ⬆️  (deps) @jeromefitz/date-fns-tz@3.0.0-canary.3 [skip ci]

- .github/actions/e2e/action.yml
- .github/actions/lint/action.yml
- package.json
- packages/design-system/package.json
- packages/lighthouse-config/lighthouse.config.js
- packages/shared/package.json
Oh der it was pulling from `@main` oh well. ✅
> 🔧  (turbo) TURBO_TELEMETRY_DISABLED [skip ci]

- sites/jeromefitzgerald.com/src/app/(notion)/about/_components/Section.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/about/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/currently/reading/_components/Book.client.tsx
- sites/jeromefitzgerald.com/src/app/playground/2024/_components/Navigation.Primary.tsx
- sites/jeromefitzgerald.com/src/store/index.tsx
Since in this new(ish) layout; this can no longer be pulled easily from API
> 🩹  NICE-122 makeshift about

- sites/jeromefitzgerald.com/src/app/(notion)/about/_components/Section.tsx
- sites/jeromefitzgerald.com/src/store/index.tsx
The thing where we need to trigger a build 😮‍💨
> 🩹  h/t mc + pl up [b]

- package.json
- pnpm-lock.yaml
https://github.com/JeromeFitz/packages/releases/tag/%40jeromefitz%2Feslint-config%405.0.0-canary.7
https://github.com/JeromeFitz/packages/releases/tag/%40jeromefitz%2Feslint-config%405.0.0-canary.6
> ⬆️  (deps) jeromefitz/eslint-config@5.0.0-canary.7 [skip ci]

- sites/jeromefitzgerald.com/src/app/(notion)/about/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/colophon/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/contact/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/currently/listening-to/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/currently/reading/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/events/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/people/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/podcasts/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/(notion)/shows/[[...catchAll]]/page.tsx
- sites/jeromefitzgerald.com/src/app/page.tsx
- sites/jeromefitzgerald.com/src/app/playground/kitchen-sink/page.tsx
This avoids the following type warning:
> "revalidate" is not a valid page prop.
> 🩹  (next) NICE-132 props hack for Page [b]

- pnpm-lock.yaml
- sites/jerandky.com/package.json
- sites/jeromefitzgerald.com/package.json
- sites/jeromefitzgerald.com/src/app/(notion)/currently/listening-to/_components/Music.client.tsx
- sites/jeromefitzgerald.com/src/app/api/v1/music/[slug]/route.ts
- sites/jeromefitzgerald.com/src/app/playground/2024/_components/Currently.Item.tsx
- sites/jeromefitzgerald.com/src/app/playground/2024/_components/Currently.Music.Client.tsx
- sites/jeromefitzgerald.com/src/app/playground/2024/_components/Currently.tsx
Haha, whoops. I had the wrong `SPOTIFY_REFRESH_TOKEN`. That is updated in all `.env` et al.
Eh, using Tidal more anyway and going away from Spotify. But until then finish up the `recently-played` route.
> 🐛 (music)  NICE-133 recently_played [b]

- sites/jeromefitzgerald.com/src/app/(pages)/about/_components/Section.tsx
- sites/jeromefitzgerald.com/src/app/(segments)/events/[...key]/_components/Event.Slug.Header.Data.tsx
- sites/jeromefitzgerald.com/src/app/(segments)/events/_components/List.tsx
- sites/jeromefitzgerald.com/src/app/layout.tsx
Guess it is time I start telling people?
> 🩹  moved to brooklyn [b]

- sites/jeromefitzgerald.com/src/app/api/v1/token-generation/apple-music/route.ts
- sites/jeromefitzgerald.com/src/lib/apple-music/get-apple-music.ts
🤮 Aye, it happens, heh.
🏗️ New build to verify latest tokens from new key secret are gucci
> 🔐  key|token rotation [skip ci]

- sites/jeromefitzgerald.com/src/app/(pages)/currently/listening-to/_components/Music.client.tsx
Library Albums do not have the same metadata.
> 🐛  (music) add library-albums to exclude list [b]
